[2022-04-15 13:52:45,975] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_2 scheduled__2020-01-22T00:00:00+00:00 [queued]>
[2022-04-15 13:52:46,871] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_2 scheduled__2020-01-22T00:00:00+00:00 [queued]>
[2022-04-15 13:52:46,878] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-15 13:52:46,918] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-04-15 13:52:46,919] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-15 13:52:47,680] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): task_2> on 2020-01-22 00:00:00+00:00
[2022-04-15 13:52:47,836] {standard_task_runner.py:52} INFO - Started process 117273 to run task
[2022-04-15 13:52:48,271] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_2', 'scheduled__2020-01-22T00:00:00+00:00', '--job-id', '111', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmpm0nab99i', '--error-file', '/tmp/tmp6eat3n1j']
[2022-04-15 13:52:48,385] {standard_task_runner.py:80} INFO - Job 111: Subtask task_2
[2022-04-15 13:52:54,113] {logging_mixin.py:109} INFO - Running <TaskInstance: parallel_dag.task_2 scheduled__2020-01-22T00:00:00+00:00 [running]> on host 10.0.2.15
[2022-04-15 13:52:57,475] {taskinstance.py:1446} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=solfa
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_2
AIRFLOW_CTX_EXECUTION_DATE=2020-01-22T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-01-22T00:00:00+00:00
[2022-04-15 13:53:00,483] {python.py:175} INFO - Done. Returned value was: None
[2022-04-15 13:53:01,271] {taskinstance.py:1278} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_2, execution_date=20200122T000000, start_date=20220415T135246, end_date=20220415T135301
[2022-04-15 13:53:02,394] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-15 13:53:04,326] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
